name: Pipeline Merge

on:
  push:
    branches: [develop]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: "main"
          commit_message_template: "🔀 MERGE: {source_ref} into target {target_branch}"